# Generated by Django 4.1.5 on 2023-04-16 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookMng", "0002_book"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="favorite",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
