# Generated by Django 4.1.5 on 2023-04-21 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookMng", "0003_book_favorite"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="rated",
            field=models.IntegerField(null=True),
        ),
    ]
